version: 2.1

orbs: 
  aws-cli: circleci/aws-cli@2.0
  aws-s3: circleci/aws-s3@3.0.0
  terraform: circleci/terraform@3.0.1

jobs:
  build-site:
    docker:
      - image: cimg/node:16.3.0
    steps:
      - checkout
      - run:
          name: "building site"
          command: |
            npm install
            npm run build
  
  lint-site:
    docker:
      - image: cimg/node:16.3.0
    steps:
      - checkout
      - run:
          name: "linting site"
          command: |
            npm install
            npm run lint

  deploy-site:
    docker:
      - image: cimg/node:16.3.0
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: "deploy"
          command: |
            npm install
            npm run build
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          from: out
          to: 's3://elliotf.dev'
      - run:
          name: "invalidate cache"
          command: |
            aws cloudfront create-invalidation --distribution-id EPJ9KZJXXXALT --paths "/*"

workflows:
  main:
    jobs:
      - build-site
      - lint-site
      - deploy-site:
          requires:
            - build-site
          filters:
            branches:
              only:
                - main